# Generated by Django 4.2.2 on 2023-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_content_post_body_post_publish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='taggedpost',
            name='tag',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['publish_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='blog.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('schedule', 'Schedule'), ('publish', 'Publish')], default='draft', max_length=8),
        ),
        migrations.DeleteModel(
            name='CategorizedPost',
        ),
        migrations.DeleteModel(
            name='TaggedPost',
        ),
    ]
