# Generated by Django 4.2.2 on 2023-06-18 12:05

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_categories_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_quill.fields.QuillField(verbose_name='body'),
        ),
    ]
