# Generated by Django 4.2.2 on 2023-06-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_settings_icon_settings_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page_title', models.CharField(max_length=255)),
                ('about_page_description', models.CharField(max_length=255)),
                ('projects_page_title', models.CharField(max_length=255)),
                ('projects_page_description', models.CharField(max_length=255)),
                ('blog_archive_title', models.CharField(max_length=255)),
                ('blog_archive_description', models.CharField(max_length=255)),
                ('category_archive_title', models.CharField(max_length=255)),
                ('category_archive_description', models.CharField(max_length=255)),
                ('tag_archive_title', models.CharField(max_length=255)),
                ('tag_archive_description', models.CharField(max_length=255)),
                ('contact_page_title', models.CharField(max_length=255)),
                ('contact_page_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Page Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('short_bio', models.TextField(blank=True, null=True)),
                ('full_bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
