# Generated by Django 4.2.2 on 2023-06-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pagesettings_sitesettings_delete_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='full_bio',
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='full_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
