# Generated by Django 4.2.2 on 2023-06-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_name_sitesettings_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagesettings',
            options={'verbose_name_plural': 'Page settings'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site settings'},
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='title',
            new_name='site_title',
        ),
        migrations.RemoveField(
            model_name='pagesettings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pagesettings',
            name='projects_page_description',
        ),
        migrations.RemoveField(
            model_name='pagesettings',
            name='projects_page_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='id',
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='projects_archive_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='projects_archive_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='setting_type',
            field=models.CharField(choices=[('page settings', 'page settings')], default='page settings', max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='setting_type',
            field=models.CharField(choices=[('site settings', 'site settings')], default='site settings', max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='about_page_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='about_page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='blog_archive_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='blog_archive_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='category_archive_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='category_archive_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='contact_page_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='contact_page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='tag_archive_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='tag_archive_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
