# Generated by Django 4.2.2 on 2023-06-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pagesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='about_page_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='experiece_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='experience_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
