# Generated by Django 4.2.2 on 2023-06-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pagesettings_about_page_subtitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagesettings',
            old_name='experiece_description',
            new_name='experience_description',
        ),
    ]
