# Generated by Django 4.2.2 on 2023-06-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_work_from_year_alter_work_to_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-start_year']},
        ),
        migrations.RenameField(
            model_name='work',
            old_name='logo',
            new_name='company_logo',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='to_year',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='position',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='from_year',
            new_name='start_year',
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='resume',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
