# Generated by Django 4.2.2 on 2023-06-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_work_options_rename_logo_work_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesettings',
            name='category_archive_description',
        ),
        migrations.RemoveField(
            model_name='pagesettings',
            name='category_archive_title',
        ),
        migrations.RemoveField(
            model_name='pagesettings',
            name='tag_archive_description',
        ),
        migrations.RemoveField(
            model_name='pagesettings',
            name='tag_archive_title',
        ),
    ]
