# Generated by Django 4.2.2 on 2023-06-27 08:52

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_pagesettings_category_archive_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='full_bio',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='setting_type',
            field=models.CharField(choices=[('page settings', 'page-settings')], default='page settings', max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='setting_type',
            field=models.CharField(choices=[('site settings', 'site-settings')], default='site settings', max_length=13, primary_key=True, serialize=False),
        ),
    ]
