# Generated by Django 4.2.2 on 2023-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_pagesettings_setting_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='setting_type',
            field=models.CharField(choices=[('page-settings', 'page-settings')], default='page-settings', max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='setting_type',
            field=models.CharField(choices=[('site-settings', 'site-settings')], default='site-settings', max_length=13, primary_key=True, serialize=False),
        ),
    ]
