# Generated by Django 4.2.2 on 2023-06-27 08:52

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
